### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by pmg102** [pmg102/pmg102.github.io#1]
- [x] Move to pmg102.github.io
- [x] Move viewport with player
- [x] Add map from mario world
- [x] Add sprites
- [x] Add DOM button controls beneath canvas
- [ ] Try on tabris.js
- [ ] Add `Sprite.touching`
- [x] Fix keyboard repeat pause http://jsfiddle.net/V2JeN/4/
- [ ] Add interaction with world objects:
  - [ ] headbutting [?]s causes:
    - [ ] coin to fly up and block to change state
    - [ ] mushroom to grow, slide along, and slowly fall offscreen 
    - [ ] flower to grow - if walked over gains 1000 points
  - [ ] monsters! spawned at defined coords, then move left.
  - [ ] coins - exist at defined coords, when intersected disappear
